package resources

import _ "embed"

// dashboardHTML contains the bundled compliance dashboard HTML.
// This file is generated by the Vite build process from ui/compliance-dashboard.
// The dist/index.html is NOT committed to git - run `task build` to generate it.
//
//go:embed dist/index.html
var dashboardHTML string
