package resources

import _ "embed"

// dashboardHTML contains the bundled compliance dashboard HTML.
// This file is generated by the Vite build process from ui/compliance-dashboard.
// Run `task build:ui` to regenerate.
//
//go:embed dist/index.html
var dashboardHTML string
